const modal=document.getElementById("modal"),content=document.getElementById("toolContent");
const tools=[
{id:"nick",cat:"nick",icon:"✦",name:"Gerador de Nick",desc:"Crie nicks estilizados com símbolos para jogos."},
{id:"whatsapp",cat:"whatsapp",icon:"↗",name:"Link do WhatsApp",desc:"Crie um link para abrir uma conversa sem salvar o número."},
{id:"qr",cat:"qr",icon:"▦",name:"QR Code",desc:"Transforme qualquer texto ou link em QR Code."},
{id:"percent",cat:"calc",icon:"%",name:"Porcentagem",desc:"Calcule porcentagens, descontos e acréscimos."},
{id:"rule3",cat:"calc",icon:"➗",name:"Regra de 3",desc:"Resolva uma regra de três automaticamente."},
{id:"salary",cat:"calc",icon:"R$",name:"Calculadora de salário",desc:"Veja descontos estimados de INSS e IRRF de forma educativa."},
{id:"discount",cat:"calc",icon:"%",name:"Desconto e acréscimo",desc:"Descubra o preço final com desconto ou aumento."},
{id:"age",cat:"calc",icon:"◌",name:"Calculadora de idade",desc:"Calcule idade e próximo aniversário."},
{id:"counter",cat:"text",icon:"Aa",name:"Contador de texto",desc:"Conte palavras, caracteres, linhas e espaços."},
{id:"upper",cat:"text",icon:"A",name:"Maiúsculas e minúsculas",desc:"Transforme seu texto em MAIÚSCULO, minúsculo ou título."},
{id:"slug",cat:"text",icon:"#",name:"Gerador de slug",desc:"Converta um título em URL amigável."},
{id:"image-compress",cat:"image",icon:"◇",name:"Comprimir imagem",desc:"Reduza o tamanho de JPG, PNG ou WebP no navegador."},
{id:"image-resize",cat:"image",icon:"↔",name:"Redimensionar imagem",desc:"Mude largura e altura de uma imagem."},
{id:"image-convert",cat:"image",icon:"◒",name:"Converter imagem",desc:"Converta imagens para JPG, PNG ou WebP."},
{id:"image-pdf",cat:"pdf",icon:"PDF",name:"Imagem → PDF",desc:"Transforme uma imagem em PDF no seu navegador."},
{id:"cv",cat:"docs",icon:"CV",name:"Gerador de currículo",desc:"Monte um currículo e salve como PDF."},
{id:"receipt",cat:"docs",icon:"↳",name:"Recibo simples",desc:"Crie um recibo pronto para imprimir ou salvar em PDF."},
{id:"declaration",cat:"docs",icon:"§",name:"Declaração",desc:"Monte uma declaração simples e imprimível."},
{id:"budget",cat:"docs",icon:"≡",name:"Orçamento",desc:"Crie um orçamento simples com itens e total."}
];

function renderTools(){
 const grid=document.getElementById("toolGrid"); grid.innerHTML=tools.map(t=>{const action=t.id==="nick"?"window.location.href='gerador-de-nick.html'":`openTool('${t.id}')`;return `<article class="card" data-cat="${t.cat}" data-name="${(t.name+" "+t.desc).toLowerCase()}"><div class="icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p><button onclick="${action}">Usar agora <span>→</span></button></article>`}).join("");
 document.getElementById("toolCount").textContent=tools.length; filterTools();
}
function openTool(type){
 modal.classList.add("show"); modal.setAttribute("aria-hidden","false");
 const T={
 whatsapp:`<div class="tool"><h2>💬 Link do WhatsApp</h2><p class="mini">Digite o número com DDD. Ex.: 77999999999</p><label>Número</label><input id="waNum" inputmode="numeric" placeholder="77999999999"><label>Mensagem (opcional)</label><textarea id="waMsg" placeholder="Olá! Vi seu contato..."></textarea><button class="action" onclick="makeWA()">Gerar link</button><div id="waResult"></div></div>`,
 qr:`<div class="tool"><h2>▦ Gerador de QR Code</h2><label>Texto ou link</label><textarea id="qrText" placeholder="https://..."></textarea><button class="action" onclick="makeQR()">Gerar QR Code</button><div id="qrResult"></div></div>`,
 percent:`<div class="tool"><h2>% Calculadora de porcentagem</h2><div class="row"><div><label>Porcentagem (%)</label><input id="pct" type="number" step="any" placeholder="10"></div><div><label>Valor</label><input id="val" type="number" step="any" placeholder="200"></div></div><button class="action" onclick="calcPct()">Calcular</button><div class="result" id="pctResult">Informe os valores.</div></div>`,
 rule3:`<div class="tool"><h2>➗ Regra de 3</h2><p>Se A corresponde a B, quanto C corresponde?</p><div class="row"><div><label>A</label><input id="a" type="number" step="any"></div><div><label>B</label><input id="b" type="number" step="any"></div></div><label>C</label><input id="c" type="number" step="any"><button class="action" onclick="calcRule()">Calcular X</button><div class="result" id="ruleResult"></div></div>`,
 discount:`<div class="tool"><h2>% Desconto ou acréscimo</h2><label>Preço</label><input id="dPrice" type="number" step="any" placeholder="100"><label>Percentual</label><input id="dPct" type="number" step="any" placeholder="10"><label>Tipo</label><select id="dType"><option value="discount">Desconto</option><option value="increase">Acréscimo</option></select><button class="action" onclick="calcDiscount()">Calcular</button><div class="result" id="dResult"></div></div>`,
 age:`<div class="tool"><h2>🎂 Calculadora de idade</h2><label>Data de nascimento</label><input id="birth" type="date"><button class="action" onclick="calcAge()">Calcular idade</button><div class="result" id="ageResult"></div></div>`,
 salary:`<div class="tool"><h2>R$ Calculadora de salário</h2><p class="mini">Simulação educacional com parâmetros ilustrativos fixos, sem garantia de atualização. Não é cálculo trabalhista oficial nem folha de pagamento. Não considera dependentes, benefícios, férias, 13º, horas extras, regras de redução/isenção ou todas as deduções.</p><label>Salário bruto</label><input id="gross" type="number" step="any" placeholder="2000"><button class="action" onclick="calcSalary()">Estimar</button><div class="result" id="salaryResult"></div></div>`,
 counter:`<div class="tool"><h2>Aa Contador de texto</h2><label>Seu texto</label><textarea id="counterText" oninput="countText()" placeholder="Digite ou cole seu texto..."></textarea><div class="result" id="counterResult">0 palavras · 0 caracteres · 0 linhas</div></div>`,
 upper:`<div class="tool"><h2>A Maiúsculas e minúsculas</h2><label>Texto</label><textarea id="caseText" placeholder="Digite seu texto..."></textarea><div class="row"><button class="action" onclick="transformCase('upper')">MAIÚSCULO</button><button class="action" onclick="transformCase('lower')">minúsculo</button></div><button class="action" onclick="transformCase('title')">Título</button><div class="result" id="caseResult"></div></div>`,
 slug:`<div class="tool"><h2># Gerador de slug</h2><label>Título</label><input id="slugText" placeholder="Meu artigo incrível"><button class="action" onclick="makeSlug()">Gerar slug</button><div class="result" id="slugResult"></div></div>`,
 "image-compress":imageTool("Comprimir imagem","compress"),
 "image-resize":imageTool("Redimensionar imagem","resize"),
 "image-convert":imageTool("Converter imagem","convert"),
 "image-pdf":imageTool("Imagem → PDF","pdf"),
 cv:`<div class="tool"><h2>📄 Gerador de currículo</h2><label>Nome completo</label><input id="cvName" placeholder="Seu nome"><label>Telefone / WhatsApp</label><input id="cvPhone" placeholder="(77) 99999-9999"><label>E-mail</label><input id="cvEmail" placeholder="seuemail@email.com"><label>Objetivo profissional</label><input id="cvObj" placeholder="Ex.: Atendimento ao cliente"><label>Sobre você</label><textarea id="cvAbout" placeholder="Apresentação curta"></textarea><label>Experiência</label><textarea id="cvExp" placeholder="Empresa, função e período"></textarea><button class="action" onclick="makeCV()">Gerar currículo</button><div id="cvResult"></div></div>`,
 receipt:`<div class="tool"><h2>🧾 Recibo simples</h2><label>Recebi de</label><input id="recFrom" placeholder="Nome"><label>Valor (R$)</label><input id="recValue" type="number" step="any" placeholder="150"><label>Referente a</label><textarea id="recFor" placeholder="Descrição do pagamento"></textarea><label>Data</label><input id="recDate" type="date"><button class="action" onclick="makeReceipt()">Gerar recibo</button><div id="recResult"></div></div>`,
 declaration:`<div class="tool"><h2>📑 Declaração</h2><label>Nome</label><input id="decName"><label>Texto da declaração</label><textarea id="decText" placeholder="Declaro para os devidos fins que..."></textarea><label>Local e data</label><input id="decPlace" placeholder="Vitória da Conquista, BA — 05/09/2026"><button class="action" onclick="makeDeclaration()">Gerar</button><div id="decResult"></div></div>`,
 budget:`<div class="tool"><h2>📋 Orçamento</h2><p class="mini">Adicione até 8 itens.</p><div id="budgetItems"></div><button class="action" onclick="addBudgetItem()">+ Adicionar item</button><button class="action" onclick="makeBudget()">Gerar orçamento</button><div id="budgetResult"></div></div>`
 };
 content.innerHTML=T[type]||"";content.querySelectorAll("input,textarea,select").forEach((field,i)=>{if(!field.id)field.id="field-"+i;const label=field.previousElementSibling;if(label?.tagName==="LABEL")label.htmlFor=field.id;else if(!field.getAttribute("aria-label"))field.setAttribute("aria-label",field.type==="file"?"Escolha uma imagem":"Campo da ferramenta")});content.querySelectorAll(".result").forEach(r=>r.setAttribute("aria-live","polite"));content.querySelector("input,textarea,select,button")?.focus(); if(type==="budget"){for(let i=0;i<3;i++)addBudgetItem()} if(type==="receipt")document.getElementById("recDate").valueAsDate=new Date();
}
function closeTool(){modal.classList.remove("show");modal.setAttribute("aria-hidden","true")}
modal.addEventListener("click",e=>{if(e.target===modal)closeTool()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeTool()});

async function copyText(text,btn){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text)}else{const area=document.createElement("textarea");area.value=text;document.body.appendChild(area);area.select();const ok=document.execCommand("copy");area.remove();if(!ok)throw Error("copy")}if(btn){const old=btn.textContent;btn.textContent="Copiado!";setTimeout(()=>btn.textContent=old,1400)}}catch{if(btn)btn.textContent="Selecione o texto e copie manualmente.";}}
function normalizePhone(value){const n=value.replace(/\D/g,"");if(/^\d{10,11}$/.test(n))return "55"+n;if(/^55\d{10,11}$/.test(n))return n;return null}
function makeWA(){const n=normalizePhone(val("waNum")),m=val("waMsg");if(!n)return show("waResult","Informe 10 ou 11 dígitos com DDD, ou 12/13 dígitos incluindo 55.");const url="https://wa.me/"+n+(m?"?text="+encodeURIComponent(m):"");document.getElementById("waResult").innerHTML=`<div class="result"><strong>Seu link:</strong><br><a href="${esc(url)}" target="_blank" rel="noopener">${esc(url)}</a><br><button class="action" onclick="copyText(${esc(JSON.stringify(url))},this)">Copiar</button></div>`}
function makeQR(){const t=val("qrText").trim();if(!t)return show("qrResult","Digite um texto ou link.");if(typeof QRCode==="undefined")return show("qrResult","A biblioteca de QR Code não carregou. Recarregue a página com conexão.");try{document.getElementById("qrResult").innerHTML='<div class="qrbox" id="qrBox"></div><button class="action" onclick="downloadQR()">Baixar QR Code</button>';new QRCode(document.getElementById("qrBox"),{text:t,width:240,height:240})}catch{show("qrResult","Texto grande demais para este QR Code. Use um texto ou link mais curto.")}}
function downloadQR(){const canvas=document.querySelector("#qrBox canvas");if(!canvas)return;const a=document.createElement("a");a.href=canvas.toDataURL("image/png");a.download="nexora-qrcode.png";a.click()}
function numberValue(id){const raw=val(id).trim();return raw===""?NaN:Number(raw)}
function calcPct(){const p=numberValue("pct"),v=numberValue("val"),result=p*v/100;show("pctResult",Number.isFinite(result)?`${fmt(p)}% de ${fmt(v)} = ${fmt(result)}`:"Preencha os dois campos com números válidos.")}
function calcRule(){const a=numberValue("a"),b=numberValue("b"),c=numberValue("c"),x=b*c/a;show("ruleResult",[a,b,c].every(Number.isFinite)&&a!==0&&Number.isFinite(x)?`X = ${fmt(x)}`:"Informe números válidos; A deve ser diferente de zero.")}
function calcDiscount(){const p=numberValue("dPrice"),q=numberValue("dPct"),type=val("dType");if(!Number.isFinite(p)||!Number.isFinite(q)||p<0||q<0||(type==="discount"&&q>100))return show("dResult","Informe preço e percentual válidos. Desconto deve estar entre 0% e 100%.");const diff=p*q/100,total=type==="discount"?p-diff:p+diff;if(!Number.isFinite(total))return show("dResult","Valores grandes demais.");show("dResult",`${type==="discount"?"Desconto":"Acréscimo"}: ${fmt(diff)}<br><strong>Preço final: ${fmt(total)}</strong>`)}
function calcAge(){const s=val("birth");const b=new Date(s+"T00:00:00"),now=new Date();now.setHours(0,0,0,0);if(!s||!Number.isFinite(b.getTime())||b>now)return show("ageResult","Informe uma data de nascimento válida, até hoje.");let age=now.getFullYear()-b.getFullYear();let next=new Date(now.getFullYear(),b.getMonth(),b.getDate());if(next>now)age--;if(next<now)next.setFullYear(next.getFullYear()+1);const days=Math.round((Date.UTC(next.getFullYear(),next.getMonth(),next.getDate())-Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))/86400000);show("ageResult",`Idade: <strong>${age} anos</strong><br>Próximo aniversário em ${days} dia(s).`)}
function calcSalary(){let g=numberValue("gross");if(!Number.isFinite(g)||!(g>0))return show("salaryResult","Informe um salário.");let inss=0,base=g;const faixas=[[1621,0.075],[2902.84,0.09],[4354.27,0.12],[8475.55,0.14]];let prev=0;for(const [lim,rate] of faixas){let part=Math.max(0,Math.min(g,lim)-prev);inss+=part*rate;prev=lim;if(g<=lim)break}inss=Math.min(inss,951.63);let irBase=g-inss;let ir=0;if(irBase>5028){ir=irBase*.275-908.73}else if(irBase>4000){ir=irBase*.225-688.11}else if(irBase>3300){ir=irBase*.15-401.6}else if(irBase>2428.8){ir=irBase*.075-182.16}ir=Math.max(0,ir);show("salaryResult",`Bruto: ${fmt(g)}<br>INSS estimado: ${fmt(inss)}<br>IRRF estimado: ${fmt(ir)}<br><strong>Líquido estimado: ${fmt(g-inss-ir)}</strong><p class="mini">Parâmetros ilustrativos não validados como tabela vigente. O resultado pode divergir do contracheque; confirme com o responsável pela folha.</p>`)}
function countText(){let t=val("counterText"),words=t.trim()?t.trim().split(/\s+/).length:0,lines=t?t.split(/\n/).length:0;show("counterResult",`${words} palavras · ${t.length} caracteres · ${lines} linhas · ${t.replace(/\s/g,"").length} sem espaços`)}
function transformCase(kind){let t=val("caseText");let out=kind==="upper"?t.toUpperCase():kind==="lower"?t.toLowerCase():t.toLowerCase().replace(/(^|[\s-])([a-zà-ÿ])/g,(m,a,b)=>a+b.toUpperCase());show("caseResult",`<textarea style="min-height:150px">${esc(out)}</textarea><br><button class="action" onclick="copyText(${esc(JSON.stringify(out))},this)">Copiar resultado</button>`)}
function makeSlug(){let s=val("slugText").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");show("slugResult",s||"Digite um título.");if(s)copyText(s)}
function imageTool(title,type){return `<div class="tool"><h2>${title}</h2><div class="drop"><input id="imgFile" type="file" accept="image/*"><p class="mini">O arquivo é processado no navegador.</p></div>${type==="resize"?'<div class="row"><div><label>Largura (px)</label><input id="imgW" type="number" placeholder="1200"></div><div><label>Altura (px)</label><input id="imgH" type="number" placeholder="800"></div></div>':type==="compress"?'<label>Qualidade</label><input id="imgQ" type="range" min="0.1" max="1" step="0.05" value="0.7"><div class="mini">Menor qualidade = arquivo menor.</div>':type==="convert"?'<label>Formato</label><select id="imgFmt"><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select>':''}<button class="action" onclick="processImage('${type}')">Processar</button><div id="imgResult"></div></div>`}
function loadImage(file){return new Promise((res,rej)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);res(img)};img.onerror=()=>{URL.revokeObjectURL(url);rej(Error("imagem inválida"))};img.src=url})}
let pdfLibraryPromise;
function loadPDFLibrary(){
 if(window.jspdf?.jsPDF)return Promise.resolve();
 if(pdfLibraryPromise)return pdfLibraryPromise;
 pdfLibraryPromise=new Promise((resolve,reject)=>{
  const script=document.createElement("script");
  const timer=setTimeout(()=>{script.remove();pdfLibraryPromise=null;reject(Error("Tempo de carregamento do PDF excedido"))},15000);
  script.src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
  script.onload=()=>{clearTimeout(timer);if(window.jspdf?.jsPDF)resolve();else{pdfLibraryPromise=null;reject(Error("PDF indisponível"))}};
  script.onerror=()=>{clearTimeout(timer);script.remove();pdfLibraryPromise=null;reject(Error("PDF indisponível"))};
  document.head.appendChild(script);
 });
 return pdfLibraryPromise;
}
async function processImage(type){const f=document.getElementById("imgFile").files[0];if(!f)return show("imgResult","Escolha uma imagem.");if(!f.type.startsWith("image/")||f.size>20*1024*1024)return show("imgResult","Escolha uma imagem de até 20 MB.");try{const img=await loadImage(f);let w=img.naturalWidth,h=img.naturalHeight;if(type==="resize"){const rw=val("imgW").trim(),rh=val("imgH").trim();w=rw?Number(rw):rh?Math.round(img.width*Number(rh)/img.height):img.width;h=rh?Number(rh):rw?Math.round(img.height*Number(rw)/img.width):img.height}if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w>8192||h>8192||w*h>16000000)return show("imgResult","Use dimensões inteiras positivas, até 8192 px por lado e 16 milhões de pixels.");const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d");const mime=type==="convert"?val("imgFmt"):"image/jpeg";if(mime==="image/jpeg"){ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h)}ctx.drawImage(img,0,0,w,h);if(type==="pdf"){show("imgResult","Preparando PDF…");await loadPDFLibrary();const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:w>=h?"landscape":"portrait",unit:"px",format:[w,h]});pdf.addImage(c.toDataURL("image/jpeg",.92),"JPEG",0,0,w,h);pdf.save("nexora-imagem.pdf");return show("imgResult","PDF criado com sucesso.")}const q=type==="compress"?Number(val("imgQ")):0.92,blob=await new Promise(resolve=>c.toBlob(resolve,mime,q));if(!blob)throw Error("exportação");if(window.nexoraImageURL)URL.revokeObjectURL(window.nexoraImageURL);const url=window.nexoraImageURL=URL.createObjectURL(blob),ext=blob.type==="image/png"?"png":blob.type==="image/webp"?"webp":"jpg";show("imgResult",`<img class="preview-img" src="${url}" alt="Prévia da imagem processada"><p>Original: ${(f.size/1024).toFixed(1)} KB · Resultado: ${(blob.size/1024).toFixed(1)} KB · ${w} × ${h} px</p><a class="hero-btn" download="nexora-imagem.${ext}" href="${url}">Baixar imagem</a>`)}catch(e){show("imgResult","Não foi possível processar. Tente uma imagem menor em JPG, PNG ou WebP.")}}
function makeCV(){let n=val("cvName")||"Seu Nome",ph=val("cvPhone"),em=val("cvEmail"),obj=val("cvObj"),ab=val("cvAbout"),ex=val("cvExp");document.getElementById("cvResult").innerHTML=`<div class="cv-preview" id="cvPrint"><h1>${esc(n)}</h1><div>${esc(ph)} ${ph&&em?" · ":""} ${esc(em)}</div><h3>OBJETIVO</h3><p>${esc(obj)}</p><h3>SOBRE</h3><p>${esc(ab)}</p><h3>EXPERIÊNCIA</h3><p>${esc(ex).replace(/\n/g,"<br>")}</p></div><button class="action" onclick="printElement('cvPrint','Currículo')">🖨 Imprimir / Salvar em PDF</button>`}
function makeReceipt(){let n=val("recFrom")||"________________",v=+val("recValue")||0,d=val("recDate"),f=val("recFor")||"________________";document.getElementById("recResult").innerHTML=`<div class="cv-preview" id="receiptPrint"><h1>RECIBO</h1><p>Recebi de <strong>${esc(n)}</strong> a importância de <strong>R$ ${fmt(v)}</strong>.</p><p>Referente a: ${esc(f)}</p><p>Data: ${esc(d)}</p><br><p>__________________________________<br>Assinatura</p></div><button class="action" onclick="printElement('receiptPrint','Recibo')">🖨 Imprimir / PDF</button>`}
function makeDeclaration(){let n=val("decName")||"________________",t=val("decText")||"Declaro para os devidos fins que ________________________________________________.",p=val("decPlace")||"________________";document.getElementById("decResult").innerHTML=`<div class="cv-preview" id="decPrint"><h1>DECLARAÇÃO</h1><p>Declaro, para os devidos fins, que <strong>${esc(n)}</strong>.</p><p>${esc(t).replace(/\n/g,"<br>")}</p><p>${esc(p)}</p><br><p>__________________________________<br>Assinatura</p></div><button class="action" onclick="printElement('decPrint','Declaração')">🖨 Imprimir / PDF</button>`}
function addBudgetItem(){const box=document.getElementById("budgetItems");if(box.children.length>=8)return;const d=document.createElement("div");d.className="row";d.innerHTML=`<div><label>Item</label><input class="biName" placeholder="Produto/serviço"></div><div><label>Valor (R$)</label><input class="biVal" type="number" step="any" placeholder="0"></div>`;box.appendChild(d)}
function makeBudget(){const ns=[...document.querySelectorAll(".biName")],vs=[...document.querySelectorAll(".biVal")];let total=0,rows="";ns.forEach((n,i)=>{let name=n.value.trim(),v=+vs[i].value||0;if(name){total+=v;rows+=`<tr><td>${esc(name)}</td><td>R$ ${fmt(v)}</td></tr>`}});if(!rows)return show("budgetResult","Adicione pelo menos um item.");document.getElementById("budgetResult").innerHTML=`<div class="cv-preview" id="budgetPrint"><h1>ORÇAMENTO</h1><table style="width:100%;border-collapse:collapse"><tbody>${rows}</tbody></table><hr><h2>Total: R$ ${fmt(total)}</h2></div><button class="action" onclick="printElement('budgetPrint','Orçamento')">🖨 Imprimir / PDF</button>`}
function printElement(id,title){const el=document.getElementById(id),w=window.open("","_blank");if(!w){alert("Permita pop-ups para abrir a impressão do documento.");return}w.document.write(`<html><head><title>${title}</title><style>body{font-family:Arial;padding:40px;color:#111;max-width:800px;margin:auto}h1{margin-bottom:12px}h3{border-bottom:1px solid #ccc;padding-bottom:5px}td{padding:10px;border-bottom:1px solid #ddd}</style></head><body>${el.innerHTML}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250)}
function show(id,html){document.getElementById(id).innerHTML=`<div class="result">${html}</div>`}
function val(id){return document.getElementById(id)?.value??""}
function fmt(n){return Number(n).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.querySelectorAll(".cat").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".cat").forEach(x=>x.classList.remove("active"));b.classList.add("active");filterTools()}));
document.getElementById("search").addEventListener("input",filterTools);
function filterTools(){const cat=document.querySelector(".cat.active").dataset.cat,q=document.getElementById("search").value.toLowerCase().trim(),hasFilter=cat!=="all"||q.length>0;let visible=0;document.querySelectorAll("#toolGrid .card").forEach(c=>{let ok=(cat==="all"||c.dataset.cat===cat)&&c.dataset.name.includes(q);c.style.display=ok?"block":"none";if(ok)visible++});const empty=document.getElementById("emptyState");empty.style.display=visible?"none":"block";empty.textContent=hasFilter?"Nenhuma ferramenta encontrada. Tente outra busca ou categoria.":"Use a busca ou selecione uma categoria para encontrar uma ferramenta."}
const searchParams=new URLSearchParams(window.location.search),initialSearch=searchParams.get("q");if(initialSearch)document.getElementById("search").value=initialSearch;renderTools();
document.querySelectorAll("[data-select-category]").forEach(link=>link.addEventListener("click",()=>{const button=document.querySelector(`.cat[data-cat="${link.dataset.selectCategory}"]`);if(button)button.click()}));
const menuToggle=document.getElementById("menuToggle"),mainNav=document.getElementById("mainNav");
menuToggle?.addEventListener("click",()=>{const isOpen=mainNav.classList.toggle("open");menuToggle.setAttribute("aria-expanded",String(isOpen));menuToggle.setAttribute("aria-label",isOpen?"Fechar menu":"Abrir menu")});
mainNav?.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{mainNav.classList.remove("open");menuToggle?.setAttribute("aria-expanded","false");menuToggle?.setAttribute("aria-label","Abrir menu")}));
